### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by pungoyal** [strongloop/strong-service-systemd#3]
My app doesn't deploy on the strongpm service. How do I check the logs?

**Comment by sam-github** [comment]
They go to wherever your system configures the, probably /var/log/...

cc: @rmg

**Comment by rmg** [comment]
If strong-pm is running as a systemd service, then you will probably need to use [journalctl](https://www.freedesktop.org/software/systemd/man/journalctl.html) to review the logs.

**Comment by pungoyal** [comment]
`journalctl -u strong-pm -f --no-tail` worked for me.
